site_name: Op-M's Experiments
site_url: https://op-m.github.io

theme:
  name: material

nav:
  - Home: index.md
  - Astronomy: astronomy.md
  - Vermicompost: worms.md
  - Gardening: garden.md
  - About: about.md

plugins:
  - search:
      indexing: 'full'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format