site_name: Op-M's Experiments

nav:
  - Home: index.md
  - Astronomy: astronomy.md
  - Vermicompost: worms.md
  - Gardening: garden.md
  - About: about.md

plugins:
  - search:
      indexing: 'full'

theme:
  name: mkdocs
  locale: en
  highlightjs: true

# markdown_extensions:
#   - toc:
#       permalink: true